{% set name = "sepaxml" %}
{% set version = "2.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sepaxml-{{ version }}.tar.gz
  sha256: 1f6f747bb4e15a12af1034964424c9cc17481127229e8d95693a5a96a3267561

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - text-unidecode
    - xmlschema

test:
  imports:
    - sepadd
    - sepaxml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelm/python-sepaxml
  summary: Python SEPA XML implementations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
