{% set name = "sepaxml" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sepaxml-{{ version }}.tar.gz
  sha256: ad8b0bad6769b820b18f9314fc01052e84d38b51affa17840b3f0b1fca2b9fcc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - text-unidecode
    - xmlschema

test:
  imports:
    - sepadd
    - sepaxml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelm/python-sepaxml
  summary: Python SEPA XML implementations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
