{% set name = "sepaxml" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sepaxml-{{ version }}.tar.gz
  sha256: b6d189c9b16d60fbaa5c79abd7e4c4e3c7b3a4b1a20571275013946e47124ed2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - text-unidecode
    - xmlschema

test:
  imports:
    - sepadd
    - sepaxml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelm/python-sepaxml
  summary: Python SEPA XML implementations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
