{% set name = "sepaxml" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sepaxml-{{ version }}.tar.gz
  sha256: 6fa18e97d21cfc27bd122d2862f2bc941501ed337603421026bd2578543bb2a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - text-unidecode
    - xmlschema

test:
  imports:
    - sepadd
    - sepaxml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelm/python-sepaxml
  summary: Python SEPA XML implementations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
